[2025-05-16T09:07:54.567+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: breweries_etl_pipeline.extract_breweries scheduled__2025-05-15T00:00:00+00:00 [queued]>
[2025-05-16T09:07:54.570+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: breweries_etl_pipeline.extract_breweries scheduled__2025-05-15T00:00:00+00:00 [queued]>
[2025-05-16T09:07:54.570+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 6
[2025-05-16T09:07:54.576+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_breweries> on 2025-05-15 00:00:00+00:00
[2025-05-16T09:07:54.580+0000] {standard_task_runner.py:60} INFO - Started process 65 to run task
[2025-05-16T09:07:54.583+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'breweries_etl_pipeline', 'extract_breweries', 'scheduled__2025-05-15T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/breweries_pipeline.py', '--cfg-path', '/tmp/tmpjtlyaexb']
[2025-05-16T09:07:54.584+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask extract_breweries
[2025-05-16T09:07:54.600+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-05-16T09:07:54.645+0000] {task_command.py:423} INFO - Running <TaskInstance: breweries_etl_pipeline.extract_breweries scheduled__2025-05-15T00:00:00+00:00 [running]> on host af93bbb00882
[2025-05-16T09:07:54.689+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='breweries_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_breweries' AIRFLOW_CTX_EXECUTION_DATE='2025-05-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-15T00:00:00+00:00'
[2025-05-16T09:07:54.690+0000] {logging_mixin.py:188} INFO - 游댳 Iniciando extra칞칚o de dados da API Open Brewery DB
[2025-05-16T09:07:54.889+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 1 extra칤da com 200 registros
[2025-05-16T09:07:55.151+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 2 extra칤da com 200 registros
[2025-05-16T09:07:55.310+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 3 extra칤da com 200 registros
[2025-05-16T09:07:55.536+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 4 extra칤da com 200 registros
[2025-05-16T09:07:55.735+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 5 extra칤da com 200 registros
[2025-05-16T09:07:55.994+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 6 extra칤da com 200 registros
[2025-05-16T09:07:56.173+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 7 extra칤da com 200 registros
[2025-05-16T09:07:56.439+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 8 extra칤da com 200 registros
[2025-05-16T09:07:56.637+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 9 extra칤da com 200 registros
[2025-05-16T09:07:56.908+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 10 extra칤da com 200 registros
[2025-05-16T09:07:57.181+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 11 extra칤da com 200 registros
[2025-05-16T09:07:57.451+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 12 extra칤da com 200 registros
[2025-05-16T09:07:57.656+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 13 extra칤da com 200 registros
[2025-05-16T09:07:57.917+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 14 extra칤da com 200 registros
[2025-05-16T09:07:58.120+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 15 extra칤da com 200 registros
[2025-05-16T09:07:58.395+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 16 extra칤da com 200 registros
[2025-05-16T09:07:58.581+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 17 extra칤da com 200 registros
[2025-05-16T09:07:58.910+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 18 extra칤da com 200 registros
[2025-05-16T09:07:59.096+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 19 extra칤da com 200 registros
[2025-05-16T09:07:59.384+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 20 extra칤da com 200 registros
[2025-05-16T09:07:59.709+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 21 extra칤da com 200 registros
[2025-05-16T09:07:59.902+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 22 extra칤da com 200 registros
[2025-05-16T09:08:00.141+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 23 extra칤da com 200 registros
[2025-05-16T09:08:00.310+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 24 extra칤da com 200 registros
[2025-05-16T09:08:00.586+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 25 extra칤da com 200 registros
[2025-05-16T09:08:00.789+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 26 extra칤da com 200 registros
[2025-05-16T09:08:01.043+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 27 extra칤da com 200 registros
[2025-05-16T09:08:01.215+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 28 extra칤da com 200 registros
[2025-05-16T09:08:01.453+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 29 extra칤da com 200 registros
[2025-05-16T09:08:01.635+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 30 extra칤da com 200 registros
[2025-05-16T09:08:01.884+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 31 extra칤da com 200 registros
[2025-05-16T09:08:02.127+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 32 extra칤da com 200 registros
[2025-05-16T09:08:02.375+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 33 extra칤da com 200 registros
[2025-05-16T09:08:02.678+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 34 extra칤da com 200 registros
[2025-05-16T09:08:02.910+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 35 extra칤da com 200 registros
[2025-05-16T09:08:03.145+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 36 extra칤da com 200 registros
[2025-05-16T09:08:03.405+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 37 extra칤da com 200 registros
[2025-05-16T09:08:03.661+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 38 extra칤da com 200 registros
[2025-05-16T09:08:03.841+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 39 extra칤da com 200 registros
[2025-05-16T09:08:04.072+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 40 extra칤da com 200 registros
[2025-05-16T09:08:04.249+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 41 extra칤da com 200 registros
[2025-05-16T09:08:04.506+0000] {logging_mixin.py:188} INFO - 九덢잺 P치gina 42 extra칤da com 170 registros
[2025-05-16T09:08:14.993+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 130, in _send_output
    self._handle_expect_response(message_body)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 176, in _handle_expect_response
    self._send_message_body(message_body)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 209, in _send_message_body
    self.send(message_body)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 223, in send
    return super().send(str)
  File "/usr/local/lib/python3.8/http/client.py", line 969, in send
    self.sock.sendall(datablock)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 130, in _send_output
    self._handle_expect_response(message_body)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 176, in _handle_expect_response
    self._send_message_body(message_body)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 209, in _send_message_body
    self.send(message_body)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 223, in send
    return super().send(str)
  File "/usr/local/lib/python3.8/http/client.py", line 969, in send
    self.sock.sendall(datablock)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/extract.py", line 38, in extract_breweries
    upload_to_s3(
  File "/opt/airflow/dags/src/s3_utils.py", line 26, in upload_to_s3
    s3.put_object(Bucket=bucket, Key=key, Body=body)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 989, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 1015, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/httpsession.py", line 503, in send
    raise ConnectionClosedError(
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "http://minio:9000/bronze/breweries_raw_20250515.json".
[2025-05-16T09:08:15.023+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=breweries_etl_pipeline, task_id=extract_breweries, execution_date=20250515T000000, start_date=20250516T090754, end_date=20250516T090815
[2025-05-16T09:08:15.055+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task extract_breweries (Connection was closed before we received a valid response from endpoint URL: "http://minio:9000/bronze/breweries_raw_20250515.json".; 65)
[2025-05-16T09:08:15.103+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-16T09:08:15.128+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
